export { default as GeneralPage } from './GeneralPage'
export { default as ErrorPage } from './ErrorPage'
export { default as PeoplePage } from './PeoplePage'
export { default as StarshipsPage } from './StarshipsPage'
export { default as PlanetsPage } from './PlanetsPage'
export { default as SingleCharPage } from './SingleCharPage'
export { default as SinglePlanetPage } from './SinglePlanetPage'
export { default as SingleStarshipPage } from './SingleStarshipPage'